python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/Japan_epoch70.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/Japan/test/images/ --conf-thres 0.3 --iou-thres 0.999 --country Japan --agnostic-nms --augment --save-csv --nosave
python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/India_epoch110.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/India/test/images/ --conf-thres 0.2 --iou-thres 0.999 --country India --agnostic-nms --augment --save-csv --nosave
python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/Czech_epoch70.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/Czech/test/images/ --conf-thres 0.2 --iou-thres 0.999 --country Czech --agnostic-nms --augment --save-csv --nosave
python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/United_epoch90.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/United_States/test/images/ --conf-thres 0.3 --iou-thres 0.999 --country United --agnostic-nms --augment --save-csv --nosave
python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/Norway_epoch110.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/Norway/test/images/ --conf-thres 0.25 --iou-thres 0.999 --country Norway --agnostic-nms --augment --save-csv --nosave
python3 detect.py --weights weights/IMSC/yolov5_anchor_epoch90.pt weights/IMSC/crddc_anchor_epoch80.pt weights/IMSC/China_epoch120.pt --img 640 --source datasets/CRDD2022/RDD2022_all_countries/China_MotorBike/test/images/ --conf-thres 0.2 --iou-thres 0.999 --country China --agnostic-nms --augment --save-csv --nosave
cp results_Japan_yolov5_anchor_epoch90_c_0.3_n_0.999_an_True_aug_True.csv leaderboard_Japan.csv
cp results_India_yolov5_anchor_epoch90_c_0.2_n_0.999_an_True_aug_True.csv leaderboard_India.csv
cp results_Czech_yolov5_anchor_epoch90_c_0.2_n_0.999_an_True_aug_True.csv leaderboard_Czech.csv
cp results_United_yolov5_anchor_epoch90_c_0.3_n_0.999_an_True_aug_True.csv leaderboard_United.csv
cp results_Norway_yolov5_anchor_epoch90_c_0.25_n_0.999_an_True_aug_True.csv leaderboard_Norway.csv
cp results_China_yolov5_anchor_epoch90_c_0.2_n_0.999_an_True_aug_True.csv leaderboard_China.csv
cat leaderboard_Japan.csv leaderboard_India.csv leaderboard_Czech.csv leaderboard_United.csv leaderboard_Norway.csv leaderboard_China.csv  > leaderboard_Overall.csv
